### ISSUE TITLE
.get() and .getJSON() with query params

### ISSUE THREAD

**Issue by eubyte** [pajax/pajax#6]
Thank you for a great library!

Would you consider adding an optional argument on .get() and .getJSON() methods to supply query params in the form of an object. The same way jQuery does it witth data: {...}?

**Comment by Dani723** [comment]
Thanks :)
Is this what you're looking for? 
https://github.com/pajax/pajax-uri

**Comment by eubyte** [comment]
Exactly... Thank you again!
